# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/base/u96v2_sbc_base.xdc

# Block Designs: bd/tima_ro_puf/tima_ro_puf.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf || ORIG_REF_NAME==tima_ro_puf} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_zynq_ultra_ps_e_0_0/tima_ro_puf_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==tima_ro_puf_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xbar_0/tima_ro_puf_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xbar_0 || ORIG_REF_NAME==tima_ro_puf_xbar_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_ps8_0_axi_periph_0/tima_ro_puf_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_ps8_0_axi_periph_0 || ORIG_REF_NAME==tima_ro_puf_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_rst_ps8_0_100M_0/tima_ro_puf_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_rst_ps8_0_100M_0 || ORIG_REF_NAME==tima_ro_puf_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_bram_ctrl_0_0/tima_ro_puf_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_bram_ctrl_0_0 || ORIG_REF_NAME==tima_ro_puf_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_bram_ctrl_0_bram_0/tima_ro_puf_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==tima_ro_puf_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_uart16550_0_0/tima_ro_puf_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_uart16550_0_0 || ORIG_REF_NAME==tima_ro_puf_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_uart16550_1_0/tima_ro_puf_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_uart16550_1_0 || ORIG_REF_NAME==tima_ro_puf_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_gpio_0_0/tima_ro_puf_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_gpio_0_0 || ORIG_REF_NAME==tima_ro_puf_axi_gpio_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_gpio_1_0/tima_ro_puf_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_gpio_1_0 || ORIG_REF_NAME==tima_ro_puf_axi_gpio_1_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_axi_gpio_2_0/tima_ro_puf_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_axi_gpio_2_0 || ORIG_REF_NAME==tima_ro_puf_axi_gpio_2_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_PWM_w_Int_0_0/tima_ro_puf_PWM_w_Int_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_PWM_w_Int_0_0 || ORIG_REF_NAME==tima_ro_puf_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_PWM_w_Int_1_0/tima_ro_puf_PWM_w_Int_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_PWM_w_Int_1_0 || ORIG_REF_NAME==tima_ro_puf_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlconcat_0_0/tima_ro_puf_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlconcat_0_0 || ORIG_REF_NAME==tima_ro_puf_xlconcat_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_0_0/tima_ro_puf_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_0_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_1_0/tima_ro_puf_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_1_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_1_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_2_0/tima_ro_puf_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_2_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_2_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_3_0/tima_ro_puf_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_3_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_3_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_4_0/tima_ro_puf_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_4_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_4_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_5_0/tima_ro_puf_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_5_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_5_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_6_0/tima_ro_puf_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_6_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_6_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_7_0/tima_ro_puf_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_7_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_7_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_8_0/tima_ro_puf_xlslice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_8_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_8_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_xlslice_9_0/tima_ro_puf_xlslice_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_xlslice_9_0 || ORIG_REF_NAME==tima_ro_puf_xlslice_9_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_clk_wiz_0_0/tima_ro_puf_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_clk_wiz_0_0 || ORIG_REF_NAME==tima_ro_puf_clk_wiz_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_0_0/tima_ro_puf_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_0_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_1_0/tima_ro_puf_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_1_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_2_0/tima_ro_puf_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_2_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_3_0/tima_ro_puf_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_3_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_4_0/tima_ro_puf_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_4_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_5_0/tima_ro_puf_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_5_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_proc_sys_reset_6_0/tima_ro_puf_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_proc_sys_reset_6_0 || ORIG_REF_NAME==tima_ro_puf_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_Tima_Ro_Puf_AXI4L_0_0/tima_ro_puf_Tima_Ro_Puf_AXI4L_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_Tima_Ro_Puf_AXI4L_0_0 || ORIG_REF_NAME==tima_ro_puf_Tima_Ro_Puf_AXI4L_0_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_0/tima_ro_puf_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_0 || ORIG_REF_NAME==tima_ro_puf_auto_ds_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_0/tima_ro_puf_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_0 || ORIG_REF_NAME==tima_ro_puf_auto_pc_0} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_1/tima_ro_puf_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_1 || ORIG_REF_NAME==tima_ro_puf_auto_ds_1} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_1/tima_ro_puf_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_1 || ORIG_REF_NAME==tima_ro_puf_auto_pc_1} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_2/tima_ro_puf_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_2 || ORIG_REF_NAME==tima_ro_puf_auto_ds_2} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_2/tima_ro_puf_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_2 || ORIG_REF_NAME==tima_ro_puf_auto_pc_2} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_3/tima_ro_puf_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_3 || ORIG_REF_NAME==tima_ro_puf_auto_ds_3} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_3/tima_ro_puf_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_3 || ORIG_REF_NAME==tima_ro_puf_auto_pc_3} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_4/tima_ro_puf_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_4 || ORIG_REF_NAME==tima_ro_puf_auto_ds_4} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_4/tima_ro_puf_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_4 || ORIG_REF_NAME==tima_ro_puf_auto_pc_4} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_5/tima_ro_puf_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_5 || ORIG_REF_NAME==tima_ro_puf_auto_ds_5} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_5/tima_ro_puf_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_5 || ORIG_REF_NAME==tima_ro_puf_auto_pc_5} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_6/tima_ro_puf_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_6 || ORIG_REF_NAME==tima_ro_puf_auto_ds_6} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_6/tima_ro_puf_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_6 || ORIG_REF_NAME==tima_ro_puf_auto_pc_6} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_ds_7/tima_ro_puf_auto_ds_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_ds_7 || ORIG_REF_NAME==tima_ro_puf_auto_ds_7} -quiet] -quiet

# IP: bd/tima_ro_puf/ip/tima_ro_puf_auto_pc_7/tima_ro_puf_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tima_ro_puf_auto_pc_7 || ORIG_REF_NAME==tima_ro_puf_auto_pc_7} -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf/u96_v2_tima_ropuf.gen/sources_1/bd/tima_ro_puf/tima_ro_puf_ooc.xdc
