#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 28 18:21:53 CEST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e21cb333c59c43e29c7e9ef6c190aee7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_tima_ro_puf_behav xil_defaultlib.tb_tima_ro_puf -log elaborate.log"
xelab -wto e21cb333c59c43e29c7e9ef6c190aee7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_tima_ro_puf_behav xil_defaultlib.tb_tima_ro_puf -log elaborate.log

