# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/u96_v2_myarbpuf.srcs/constraints.xdc

# Block Designs: bd/u96v2_myarbpuf/u96v2_myarbpuf.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf || ORIG_REF_NAME==u96v2_myarbpuf} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_zynq_ultra_ps_e_0_0/u96v2_myarbpuf_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xbar_0/u96v2_myarbpuf_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xbar_0 || ORIG_REF_NAME==u96v2_myarbpuf_xbar_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_ps8_0_axi_periph_0/u96v2_myarbpuf_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_ps8_0_axi_periph_0 || ORIG_REF_NAME==u96v2_myarbpuf_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_rst_ps8_0_100M_0/u96v2_myarbpuf_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_rst_ps8_0_100M_0 || ORIG_REF_NAME==u96v2_myarbpuf_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_bram_ctrl_0_0/u96v2_myarbpuf_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_bram_ctrl_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_bram_ctrl_0_bram_0/u96v2_myarbpuf_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_uart16550_0_0/u96v2_myarbpuf_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_uart16550_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_uart16550_1_0/u96v2_myarbpuf_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_uart16550_1_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_gpio_0_0/u96v2_myarbpuf_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_gpio_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_gpio_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_gpio_1_0/u96v2_myarbpuf_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_gpio_1_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_gpio_1_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_axi_gpio_2_0/u96v2_myarbpuf_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_axi_gpio_2_0 || ORIG_REF_NAME==u96v2_myarbpuf_axi_gpio_2_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_PWM_w_Int_0_0/u96v2_myarbpuf_PWM_w_Int_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_PWM_w_Int_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_PWM_w_Int_1_0/u96v2_myarbpuf_PWM_w_Int_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_PWM_w_Int_1_0 || ORIG_REF_NAME==u96v2_myarbpuf_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlconcat_0_0/u96v2_myarbpuf_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlconcat_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlconcat_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_0_0/u96v2_myarbpuf_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_1_0/u96v2_myarbpuf_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_1_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_1_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_2_0/u96v2_myarbpuf_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_2_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_2_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_3_0/u96v2_myarbpuf_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_3_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_3_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_4_0/u96v2_myarbpuf_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_4_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_4_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_5_0/u96v2_myarbpuf_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_5_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_5_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_6_0/u96v2_myarbpuf_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_6_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_6_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_7_0/u96v2_myarbpuf_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_7_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_7_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_8_0/u96v2_myarbpuf_xlslice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_8_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_8_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_xlslice_9_0/u96v2_myarbpuf_xlslice_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_xlslice_9_0 || ORIG_REF_NAME==u96v2_myarbpuf_xlslice_9_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_clk_wiz_0_0/u96v2_myarbpuf_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_clk_wiz_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_clk_wiz_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_0_0/u96v2_myarbpuf_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_1_0/u96v2_myarbpuf_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_1_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_2_0/u96v2_myarbpuf_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_2_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_3_0/u96v2_myarbpuf_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_3_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_4_0/u96v2_myarbpuf_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_4_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_5_0/u96v2_myarbpuf_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_5_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_proc_sys_reset_6_0/u96v2_myarbpuf_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_proc_sys_reset_6_0 || ORIG_REF_NAME==u96v2_myarbpuf_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_My_First_Arb_Puf_0_0/u96v2_myarbpuf_My_First_Arb_Puf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_My_First_Arb_Puf_0_0 || ORIG_REF_NAME==u96v2_myarbpuf_My_First_Arb_Puf_0_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_0/u96v2_myarbpuf_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_0 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_0/u96v2_myarbpuf_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_0 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_0} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_1/u96v2_myarbpuf_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_1 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_1} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_1/u96v2_myarbpuf_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_1 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_1} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_2/u96v2_myarbpuf_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_2 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_2} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_2/u96v2_myarbpuf_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_2 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_2} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_3/u96v2_myarbpuf_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_3 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_3} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_3/u96v2_myarbpuf_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_3 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_3} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_4/u96v2_myarbpuf_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_4 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_4} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_4/u96v2_myarbpuf_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_4 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_4} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_5/u96v2_myarbpuf_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_5 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_5} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_5/u96v2_myarbpuf_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_5 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_5} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_6/u96v2_myarbpuf_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_6 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_6} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_6/u96v2_myarbpuf_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_6 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_6} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_ds_7/u96v2_myarbpuf_auto_ds_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_ds_7 || ORIG_REF_NAME==u96v2_myarbpuf_auto_ds_7} -quiet] -quiet

# IP: bd/u96v2_myarbpuf/ip/u96v2_myarbpuf_auto_pc_7/u96v2_myarbpuf_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96v2_myarbpuf_auto_pc_7 || ORIG_REF_NAME==u96v2_myarbpuf_auto_pc_7} -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_myarbpuf/u96_v2_myarbpuf.gen/sources_1/bd/u96v2_myarbpuf/u96v2_myarbpuf_ooc.xdc
