# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.srcs/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2.xci
# IP: The module: 'u96_v2_tima_ropuf2_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.gen/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_tima_ropuf2_auto_ds_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.gen/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_tima_ropuf2_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.srcs/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2.xci
# IP: The module: 'u96_v2_tima_ropuf2_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.gen/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_tima_ropuf2_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_tima_ropuf2/u96_v2_tima_ropuf2.gen/sources_1/bd/u96_v2_tima_ropuf2/ip/u96_v2_tima_ropuf2_auto_ds_2/u96_v2_tima_ropuf2_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_tima_ropuf2_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
