# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.srcs/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0.xci
# IP: The module: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.srcs/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0.xci
# IP: The module: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_4tima_ropuf2_axi_uart16550_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
