#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 10 00:24:51 CEST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 83bd324f2c2349f5846d9bdcca6b1cc5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_DB_behav xil_defaultlib.tb_top_DB -log elaborate.log"
xelab -wto 83bd324f2c2349f5846d9bdcca6b1cc5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_DB_behav xil_defaultlib.tb_top_DB -log elaborate.log

