#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : u96v2_arbutterfly.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Oct 09 22:47:47 CEST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: u96v2_arbutterfly.sh [-help]
# usage: u96v2_arbutterfly.sh [-lib_map_path]
# usage: u96v2_arbutterfly.sh [-noclean_files]
# usage: u96v2_arbutterfly.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'u96v2_arbutterfly.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 zynq_ultra_ps_e_vip_v1_0_8 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_bram_ctrl_v4_1_4 blk_mem_gen_v8_4_4 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_24 interrupt_control_v3_1_4 axi_gpio_v2_0_24 xlconcat_v2_1_4 xlslice_v1_0_2 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 axi_dwidth_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "u96v2_arbutterfly.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/puftester/tools/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_zynq_ultra_ps_e_0_0/sim/u96v2_arbutterfly_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xbar_0/sim/u96v2_arbutterfly_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_rst_ps8_0_100M_0/sim/u96v2_arbutterfly_rst_ps8_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_1_4 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/c9f0/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_bram_ctrl_0_0/sim/u96v2_arbutterfly_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_bram_ctrl_0_bram_0/sim/u96v2_arbutterfly_axi_bram_ctrl_0_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uart16550_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/df78/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_uart16550_0_0/sim/u96v2_arbutterfly_axi_uart16550_0_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_uart16550_1_0/sim/u96v2_arbutterfly_axi_uart16550_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_gpio_0_0/sim/u96v2_arbutterfly_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_gpio_1_0/sim/u96v2_arbutterfly_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_axi_gpio_2_0/sim/u96v2_arbutterfly_axi_gpio_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/d813/hdl/verilog/PWM_Controller_Int.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/d813/hdl/vhdl/PWM_w_Int_S00_AXI.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/d813/hdl/vhdl/PWM_w_Int.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_PWM_w_Int_0_0/sim/u96v2_arbutterfly_PWM_w_Int_0_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_PWM_w_Int_1_0/sim/u96v2_arbutterfly_PWM_w_Int_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlconcat_0_0/sim/u96v2_arbutterfly_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_0_0/sim/u96v2_arbutterfly_xlslice_0_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_1_0/sim/u96v2_arbutterfly_xlslice_1_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_2_0/sim/u96v2_arbutterfly_xlslice_2_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_3_0/sim/u96v2_arbutterfly_xlslice_3_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_4_0/sim/u96v2_arbutterfly_xlslice_4_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_5_0/sim/u96v2_arbutterfly_xlslice_5_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_6_0/sim/u96v2_arbutterfly_xlslice_6_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_7_0/sim/u96v2_arbutterfly_xlslice_7_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_8_0/sim/u96v2_arbutterfly_xlslice_8_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_xlslice_9_0/sim/u96v2_arbutterfly_xlslice_9_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_clk_wiz_0_0/u96v2_arbutterfly_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_clk_wiz_0_0/u96v2_arbutterfly_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_0_0/sim/u96v2_arbutterfly_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_1_0/sim/u96v2_arbutterfly_proc_sys_reset_1_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_2_0/sim/u96v2_arbutterfly_proc_sys_reset_2_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_3_0/sim/u96v2_arbutterfly_proc_sys_reset_3_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_4_0/sim/u96v2_arbutterfly_proc_sys_reset_4_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_5_0/sim/u96v2_arbutterfly_proc_sys_reset_5_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_proc_sys_reset_6_0/sim/u96v2_arbutterfly_proc_sys_reset_6_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/1bMux.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/hdl/ArButterfly_PUF_v1_0_PUF_AXI.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/Arbiter.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/Butterfly.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/DFF.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/Puf.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/src/top_puf.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ipshared/7571/hdl/ArButterfly_PUF_v1_0.vhd" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_ArButterfly_PUF_0_0/sim/u96v2_arbutterfly_ArButterfly_PUF_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/da1e/hdl" +incdir+"$ref_dir/../../../../u96_v2_arbutterfly_puf.gen/sources_1/bd/u96v2_arbutterfly/ipshared/d0f7" +incdir+"/home/puftester/tools/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_0/sim/u96v2_arbutterfly_auto_ds_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_0/sim/u96v2_arbutterfly_auto_pc_0.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_1/sim/u96v2_arbutterfly_auto_ds_1.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_1/sim/u96v2_arbutterfly_auto_pc_1.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_2/sim/u96v2_arbutterfly_auto_ds_2.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_2/sim/u96v2_arbutterfly_auto_pc_2.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_3/sim/u96v2_arbutterfly_auto_ds_3.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_3/sim/u96v2_arbutterfly_auto_pc_3.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_4/sim/u96v2_arbutterfly_auto_ds_4.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_4/sim/u96v2_arbutterfly_auto_pc_4.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_5/sim/u96v2_arbutterfly_auto_ds_5.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_5/sim/u96v2_arbutterfly_auto_pc_5.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_6/sim/u96v2_arbutterfly_auto_ds_6.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_6/sim/u96v2_arbutterfly_auto_pc_6.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_ds_7/sim/u96v2_arbutterfly_auto_ds_7.v" \
    "$ref_dir/../../../bd/u96v2_arbutterfly/ip/u96v2_arbutterfly_auto_pc_7/sim/u96v2_arbutterfly_auto_pc_7.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/u96v2_arbutterfly/sim/u96v2_arbutterfly.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.u96v2_arbutterfly xil_defaultlib.glbl -o u96v2_arbutterfly_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./u96v2_arbutterfly_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./u96v2_arbutterfly.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_arbutterfly_puf/u96_v2_arbutterfly_puf.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key u96v2_arbutterfly_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc u96v2_arbutterfly_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./u96v2_arbutterfly.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: u96v2_arbutterfly.sh [-help]\n\
Usage: u96v2_arbutterfly.sh [-lib_map_path]\n\
Usage: u96v2_arbutterfly.sh [-reset_run]\n\
Usage: u96v2_arbutterfly.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
