set_property SRC_FILE_INFO {cfile:/home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4x4_apuf/u96_v2_4x4_apuf.srcs/constrs_1/imports/4x4_arb_puf.srcs/constraints.xdc rfile:../../../u96_v2_4x4_apuf.srcs/constrs_1/imports/4x4_arb_puf.srcs/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_ENABLED_FALSE [get_drc_checks LUTLP-1]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports bt_ctsn]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports bt_rtsn]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports ls_mezz_uart0_rx]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports ls_mezz_uart0_tx]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5 [get_ports ls_mezz_uart1_rx]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports ls_mezz_uart1_tx]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {ls_mezz_rst[1]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7 [get_ports {ls_mezz_rst[0]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {ls_mezz_int[0]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports {ls_mezz_int[1]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A6 [get_ports {ls_mezz_pwm0[0]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {ls_mezz_pwm1[0]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports {wifi_en_led_tri_o[0]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {bt_en_led_tri_o[0]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {fan_pwm_tri_o[0]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports {hs_mezz_csi0_c[0]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P1 [get_ports {hs_mezz_csi0_c[1]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {hs_mezz_csi0_d[0]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {hs_mezz_csi0_d[1]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {hs_mezz_csi0_d[2]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {hs_mezz_csi0_d[3]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M5 [get_ports {hs_mezz_csi0_d[4]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {hs_mezz_csi0_d[5]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {hs_mezz_csi0_d[6]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {hs_mezz_csi0_d[7]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {hs_mezz_csi1_c[0]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T2 [get_ports {hs_mezz_csi1_c[1]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {hs_mezz_csi1_d[0]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {hs_mezz_csi1_d[1]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {hs_mezz_csi1_d[2]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {hs_mezz_csi1_d[3]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E8 [get_ports {hs_mezz_csi0_mclk[0]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {hs_mezz_csi1_mclk[0]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {hs_mezz_dsi_clk[1]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H5 [get_ports {hs_mezz_dsi_clk[0]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {hs_mezz_dsi_d[0]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F1 [get_ports {hs_mezz_dsi_d[1]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E4 [get_ports {hs_mezz_dsi_d[2]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {hs_mezz_dsi_d[3]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {hs_mezz_dsi_d[4]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {hs_mezz_dsi_d[5]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {hs_mezz_dsi_d[6]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C3 [get_ports {hs_mezz_dsi_d[7]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {hs_mezz_hsic_str[0]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {hs_mezz_hsic_d[0]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y179 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y179 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y179 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y179 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/FIRST_SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y178 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y178 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y178 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y178 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[1].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y177 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y177 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y177 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y177 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[2].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y176 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y176 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y176 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y176 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[3].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y175 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[0].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y175 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[1].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y175 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[2].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y175 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/SWITCH_BLOCKS[4].SWITCH_BLOCK/EQUAL_PATHS[3].EQUAL_PATH_MUX/Q_INST_0]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF2 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_2_1/Q_reg]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_2_1/Q_reg]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_3_1/Q_reg]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_3_1/Q_reg]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF2 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_3_2/Q_reg]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_3_2/Q_reg]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_1/Q_reg]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_1/Q_reg]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF2 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_2/Q_reg]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_2/Q_reg]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_3/Q_reg]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X0Y174 [get_cells u96v2_4x4_apuf_i/Arb_Puf_4x4_0/U0/Arb_Puf_4x4_v1_0_PUF_AXI_inst/ARBITER_PUF_4x4/APUF_TEST_UNIT/APUF_ARBITER/FF_4_3/Q_reg]
