# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.srcs/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0.xci
# IP: The module: 'u96_v2_pop_ropuf_proc_sys_reset_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.srcs/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0.xci
# IP: The module: 'u96_v2_pop_ropuf_proc_sys_reset_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/puftester/PhD/repo/Hw-designs/Platforms/Ultra96v2/u96_v2_pop_ro_puf/u96_v2_pop_ro_puf.gen/sources_1/bd/u96_v2_pop_ropuf/ip/u96_v2_pop_ropuf_proc_sys_reset_6_0/u96_v2_pop_ropuf_proc_sys_reset_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u96_v2_pop_ropuf_proc_sys_reset_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
