# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/base/u96v2_sbc_base.xdc

# Block Designs: bd/u96_v2_4tima_ropuf2/u96_v2_4tima_ropuf2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2 || ORIG_REF_NAME==u96_v2_4tima_ropuf2} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_zynq_ultra_ps_e_0_0/u96_v2_4tima_ropuf2_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xbar_0/u96_v2_4tima_ropuf2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xbar_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xbar_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_ps8_0_axi_periph_0/u96_v2_4tima_ropuf2_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_ps8_0_axi_periph_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_rst_ps8_0_100M_0/u96_v2_4tima_ropuf2_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_rst_ps8_0_100M_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_bram_ctrl_0_0/u96_v2_4tima_ropuf2_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_bram_ctrl_0_bram_0/u96_v2_4tima_ropuf2_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_0_0/u96_v2_4tima_ropuf2_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_uart16550_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_uart16550_1_0/u96_v2_4tima_ropuf2_axi_uart16550_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_uart16550_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_gpio_0_0/u96_v2_4tima_ropuf2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_gpio_1_0/u96_v2_4tima_ropuf2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_axi_gpio_2_0/u96_v2_4tima_ropuf2_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_2_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_axi_gpio_2_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_PWM_w_Int_0_0/u96_v2_4tima_ropuf2_PWM_w_Int_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_PWM_w_Int_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_PWM_w_Int_1_0/u96_v2_4tima_ropuf2_PWM_w_Int_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_PWM_w_Int_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlconcat_0_0/u96_v2_4tima_ropuf2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlconcat_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlconcat_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_0_0/u96_v2_4tima_ropuf2_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_1_0/u96_v2_4tima_ropuf2_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_2_0/u96_v2_4tima_ropuf2_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_2_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_2_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_3_0/u96_v2_4tima_ropuf2_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_3_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_3_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_4_0/u96_v2_4tima_ropuf2_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_4_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_4_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_5_0/u96_v2_4tima_ropuf2_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_5_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_5_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_6_0/u96_v2_4tima_ropuf2_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_6_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_6_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_7_0/u96_v2_4tima_ropuf2_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_7_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_7_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_8_0/u96_v2_4tima_ropuf2_xlslice_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_8_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_8_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_xlslice_9_0/u96_v2_4tima_ropuf2_xlslice_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_xlslice_9_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_xlslice_9_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_clk_wiz_0_0/u96_v2_4tima_ropuf2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_clk_wiz_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_0_0/u96_v2_4tima_ropuf2_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_1_0/u96_v2_4tima_ropuf2_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_2_0/u96_v2_4tima_ropuf2_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_2_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_3_0/u96_v2_4tima_ropuf2_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_3_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_4_0/u96_v2_4tima_ropuf2_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_4_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_5_0/u96_v2_4tima_ropuf2_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_5_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_proc_sys_reset_6_0/u96_v2_4tima_ropuf2_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_6_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_tima_ro_0_0/u96_v2_4tima_ropuf2_tima_ro_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_tima_ro_0_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_tima_ro_0_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_tima_ro_1_0/u96_v2_4tima_ropuf2_tima_ro_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_tima_ro_1_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_tima_ro_1_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_tima_ro_2_0/u96_v2_4tima_ropuf2_tima_ro_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_tima_ro_2_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_tima_ro_2_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_tima_ro_3_0/u96_v2_4tima_ropuf2_tima_ro_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_tima_ro_3_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_tima_ro_3_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_0/u96_v2_4tima_ropuf2_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_0/u96_v2_4tima_ropuf2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_0 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_0} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_1/u96_v2_4tima_ropuf2_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_1 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_1} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_1/u96_v2_4tima_ropuf2_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_1 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_1} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_2/u96_v2_4tima_ropuf2_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_2 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_2} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_2/u96_v2_4tima_ropuf2_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_2 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_2} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_3/u96_v2_4tima_ropuf2_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_3 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_3} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_3/u96_v2_4tima_ropuf2_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_3 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_3} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_4/u96_v2_4tima_ropuf2_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_4 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_4} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_4/u96_v2_4tima_ropuf2_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_4 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_4} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_5/u96_v2_4tima_ropuf2_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_5 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_5} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_5/u96_v2_4tima_ropuf2_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_5 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_5} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_6/u96_v2_4tima_ropuf2_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_6 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_6} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_6/u96_v2_4tima_ropuf2_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_6 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_6} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_7/u96_v2_4tima_ropuf2_auto_ds_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_7 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_7} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_7/u96_v2_4tima_ropuf2_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_7 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_7} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_8/u96_v2_4tima_ropuf2_auto_ds_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_8 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_8} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_8/u96_v2_4tima_ropuf2_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_8 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_8} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_9/u96_v2_4tima_ropuf2_auto_ds_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_9 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_9} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_9/u96_v2_4tima_ropuf2_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_9 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_9} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_ds_10/u96_v2_4tima_ropuf2_auto_ds_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_ds_10 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_ds_10} -quiet] -quiet

# IP: bd/u96_v2_4tima_ropuf2/ip/u96_v2_4tima_ropuf2_auto_pc_10/u96_v2_4tima_ropuf2_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u96_v2_4tima_ropuf2_auto_pc_10 || ORIG_REF_NAME==u96_v2_4tima_ropuf2_auto_pc_10} -quiet] -quiet

# XDC: /home/daniele/Repo/Hw-designs/Platforms/Ultra96v2/u96_v2_4xtimaropuf2/u96_v2_4xtimaropuf2.gen/sources_1/bd/u96_v2_4tima_ropuf2/u96_v2_4tima_ropuf2_ooc.xdc
