#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Oct 09 21:35:03 CEST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_puf_time_synth -key {Post-Synthesis:sim_1:Timing:tb_top_puf} -tclbatch tb_top_puf.tcl -log simulate.log"
xsim tb_top_puf_time_synth -key {Post-Synthesis:sim_1:Timing:tb_top_puf} -tclbatch tb_top_puf.tcl -log simulate.log

