webtalk_init -webtalk_dir /home/puftester/PhD/repo/Hw-designs/PUFs/tima_ro_puf_2/tima_ro_puf_2.sim/sim_1/behav/xsim/xsim.dir/tb_tima_ro_puf_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep 28 18:25:50 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "da5f62a4-b64e-4d6f-ac7a-d8a3127c9786" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e21cb333c59c43e29c7e9ef6c190aee7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1932.220 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "10000" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.94_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "143268_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1748022988 -regid "" -xml /home/puftester/PhD/repo/Hw-designs/PUFs/tima_ro_puf_2/tima_ro_puf_2.sim/sim_1/behav/xsim/xsim.dir/tb_tima_ro_puf_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/puftester/PhD/repo/Hw-designs/PUFs/tima_ro_puf_2/tima_ro_puf_2.sim/sim_1/behav/xsim/xsim.dir/tb_tima_ro_puf_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/puftester/PhD/repo/Hw-designs/PUFs/tima_ro_puf_2/tima_ro_puf_2.sim/sim_1/behav/xsim/xsim.dir/tb_tima_ro_puf_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
