#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 09 22:32:23 CEST 2024
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 3b4cb2963bd04272a241049259b388dd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_puf_behav xil_defaultlib.tb_top_puf -log elaborate.log"
xelab -wto 3b4cb2963bd04272a241049259b388dd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_top_puf_behav xil_defaultlib.tb_top_puf -log elaborate.log

